ASPCoreMvcSamples/MVCSampleApp/Controllers/ViewsDemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCSampleApp.Models;

namespace MVCSampleApp.Controllers
{
    public class ViewsDemoController : Controller
    {
        private EventsAndMenusContext _context;

        /// <summary>
        /// 依赖注入EventsAndMenusContext
        /// </summary>
        /// <param name="context"></param>
        public ViewsDemoController(EventsAndMenusContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PassingData()
        {
            ViewBag.MyData = "从控制器传递了数据";
            return View();
        }

        public IActionResult PassingAModel() => View(GetSampleData());

        private IEnumerable<Menu> GetSampleData() =>
            new List<Menu>
            {
                new Menu
                {
                    Id = 1,
                    Text = "宫保鸡丁",
                    Price = 6.9,
                    Category = "Main"
                },
                new Menu
                {
                    Id = 2,
                    Text = "水煮牛肉",
                    Price = 6.9,
                    Category = "Main"
                },
                 new Menu
                {
                    Id = 3,
                    Text = "辣炒蛤蜊",
                    Price = 6.9,
                    Category = "Main"
                }
            };

        public IActionResult LayoutSample() => View();

        public IActionResult LayoutUsingSections() => View();

        public IActionResult UseAPartialView1() => View(_context);
        public ActionResult UseAPartialView2() => View();
        public ActionResult ShowEvents()
        {
            ViewBag.EventsTitle = "Live Events";
            return PartialView(_context.Events);
        }

        public IActionResult UseViewComponent1() => View();
        public IActionResult UseViewComponent2() => View();
        public IActionResult InjectServiceInView() => View();
    }
}

ASPCoreMvcSamples/MVCSampleApp/ViewComponents/EventListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVCSampleApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCSampleApp.ViewComponents
{
    public class EventListViewComponent : ViewComponent
    {
        //需要在Startup中注册的EventsAndMenusContext类型。
        private readonly EventsAndMenusContext _context;
        public EventListViewComponent(EventsAndMenusContext context)
        {
            _context = context;
        }
        /// <summary>
        /// InvokeAsync方法定义为从显示ViewComponent的View中调用。
        /// 此方法可以包含任何数量和类型的参数，因为IViewComponentHelper接口定义的方法使用params关键字定义了灵活数量的参数。
        /// 也可以使用同步实现此方法，返回的是IViewComponentResult。
        /// 最好使用异步，例如访问数据库。
        /// view component需要存储在ViewComponents目录中。 该目录本身可以放在项目中的任何位置
        /// </summary>
        /// <param name="from"></param>
        /// <param name="to"></param>
        /// <returns></returns>
        public Task<IViewComponentResult> InvokeAsync(DateTime from, DateTime to) =>
            Task.FromResult<IViewComponentResult>(View(EventsByDateRange(from, to)));
        private IEnumerable<Event> EventsByDateRange(DateTime from, DateTime to) =>
            _context.Events.Where(e => e.Day >= from && e.Day <= to);
    }
}

ASPCoreMvcSamples/MVCSampleApp/Views/ViewsDemo/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

ASPCoreMvcSamples/MVCSampleApp/Views/ViewsDemo/InjectServiceInView.cshtml
@using MVCSampleApp.Services
@inject ISampleService sampleService
<p>
    @string.Join(" * ", sampleService.GetSampleStrings())
</p>

ASPCoreMvcSamples/MVCSampleApp/Views/ViewsDemo/LayoutSample.cshtml
@{
    ViewData["Title"] = "LayoutSample";
}

<h2>LayoutSample</h2>

ASPCoreMvcSamples/MVCSampleApp/Views/ViewsDemo/LayoutUsingSections.cshtml
@{
    ViewBag.Title = "Layout Using Sections";
} 
<h2>使用Sections的Layout</h2>
<div>这是主要内容</div>
@section PageNavigation
    {
    <div>拥有Navigation的View</div>
    <ul>
        <li>Nav1</li>
        <li>Nav2</li>
    </ul>
}

ASPCoreMvcSamples/MVCSampleApp/Views/ViewsDemo/PassingAModel.cshtml
@using MVCSampleApp.Models
@model IEnumerable<Menu>
@{
    ViewData["Title"] = "PassingAModel";
}

<div>
    <ul>
        @foreach (var item in Model)
        {
            <li>@item.Text</li>
        }
    </ul>
</div>

ASPCoreMvcSamples/MVCSampleApp/Views/ViewsDemo/PassingData.cshtml
@{
    ViewData["Title"] = "PassingData";
}

<h2>@ViewBag.MyData</h2>

ASPCoreMvcSamples/MVCSampleApp/Views/ViewsDemo/ShowEvents.cshtml
@using MVCSampleApp.Models
@model IEnumerable<Event>

<h2>@ViewBag.EventsTitle</h2>
<table>
    @foreach (var item in Model)
    {
    <tr>
        <td>@item.Day.ToShortDateString()</td>
        <td>@item.Text</td>
    </tr>
    }
</table>

ASPCoreMvcSamples/MVCSampleApp/Views/ViewsDemo/UseAPartialView1.cshtml
@using MVCSampleApp.Models
@model EventsAndMenusContext
@{
    ViewBag.Title = "Use a Partial View";
    ViewBag.EventsTitle = "Live Events";
} 
<h2>使用部分视图</h2>
<div>主视图</div>
<div>
    @await Html.PartialAsync("ShowEvents", Model.Events)
</div>

ASPCoreMvcSamples/MVCSampleApp/Views/ViewsDemo/UseAPartialView2.cshtml
@using MVCSampleApp.Models
@model EventsAndMenusContext
@{
    ViewBag.Title = "Use a Partial View";
} 
<script src="~/lib/jquery/dist/jquery.js"></script>
<script>
    (function () {
        window.onload = function () {
            var buttonEvents = document.getElementById("getEvents");
            buttonEvents.onclick = function () {
                if (window.fetch == null) {
                    output.innerHTML = "<div>window.fetch not supported. Use another browser</div>";
                    return;
                }
                //利用fetch代替Ajax从服务器下载部分视图
                var result = fetch("/ViewsDemo/ShowEvents");
                result.then(function (response){
                    return response.text();
                }).then(function (text){
                    var output = document.getElementById("output");
                        output.innerHTML = text;});
            };
        };
    })();
</script>
<h2>使用部分视图</h2>
<div>主页面</div>
<button id="getEvents">加载部分视图按钮</button>
<div id="output">
</div>

ASPCoreMvcSamples/MVCSampleApp/Views/ViewsDemo/UseViewComponent1.cshtml
@{
    ViewBag.Title = "View Components Sample";
} 
<h2>@ViewBag.Title</h2>
<p>
    @*Component是View的动态创建属性(dynamically created property)，它返回实现IViewComponentHelper的对象。
    IViewComponentHelper允许调用同步或异步方法
    需要使用Dictionary <string，object>传递参数，其中键与参数名称匹配*@
        @await Component.InvokeAsync("EventList", new
        Dictionary<string, object>()
        {
        ["from"] = new DateTime(2018, 4, 1),
        ["to"] = new DateTime(2018, 4, 20)
        })
</p>

ASPCoreMvcSamples/MVCSampleApp/Views/ViewsDemo/UseViewComponent2.cshtml
@addTagHelper *, MVCSampleApp
@{
    ViewBag.Title = "View Components Sample";
} 
<h2>@ViewBag.Title</h2>
<vc:event-list from="@new DateTime(2018, 4, 1)" to="@new DateTime(2018, 4, 20)" />