ASPCoreMvcSamples/MVCSampleApp/Controllers/ViewsDemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCSampleApp.Models;

namespace MVCSampleApp.Controllers
{
    public class ViewsDemoController : Controller
    {
        private EventsAndMenusContext _context;

        /// <summary>
        /// 依赖注入EventsAndMenusContext
        /// </summary>
        /// <param name="context"></param>
        public ViewsDemoController(EventsAndMenusContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PassingData()
        {
            ViewBag.MyData = "从控制器传递了数据";
            return View();
        }

        public IActionResult PassingAModel() => View(GetSampleData());

        private IEnumerable<Menu> GetSampleData() =>
            new List<Menu>
            {
                new Menu
                {
                    Id = 1,
                    Text = "宫保鸡丁",
                    Price = 6.9,
                    Category = "Main"
                },
                new Menu
                {
                    Id = 2,
                    Text = "水煮牛肉",
                    Price = 6.9,
                    Category = "Main"
                },
                 new Menu
                {
                    Id = 3,
                    Text = "辣炒蛤蜊",
                    Price = 6.9,
                    Category = "Main"
                }
            };

        public IActionResult LayoutSample() => View();

        public IActionResult LayoutUsingSections() => View();

        public IActionResult UseAPartialView1() => View(_context);
        public ActionResult UseAPartialView2() => View();
        public ActionResult ShowEvents()
        {
            ViewBag.EventsTitle = "Live Events";
            return PartialView(_context.Events);
        }

        public IActionResult UseViewComponent1() => View();
        public IActionResult UseViewComponent2() => View();
        public IActionResult InjectServiceInView() => View();
    }
}

ASPCoreMvcSamples/MVCSampleApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initialscale=1.0" />
    <title>@ViewBag.Title</title>
    <environment include="Development">
        <link rel="stylesheet"
              href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallbackhref=" ~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-testproperty="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" aspappend-version="true" />
    </environment>
    <title>@ViewBag.Title - My ASP.NET Application</title>
</head>
<body>
    <div class="container body-content">
        <header>
            <h1>ASP .NET MVC例子</h1>
        </header>
        <nav>
            <ul>
                <li><a asp-controller="ViewsDemo" asp-action="LayoutSample">LayoutSample</a></li>
                <li><a asp-controller="ViewsDemo" asp-action="LayoutUsingSections">Layout Using Sections</a></li>
            </ul>
        </nav>
        <div>
            @RenderSection("PageNavigation", required: false)
        </div>
        <div>
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>
                <div>MVC 例子</div> @DateTime.Now.Year - My ASP.NET Application
            </p>
        </footer>
    </div>
</body>
</html>